CREATE TABLE resources (
    id INT AUTO_INCREMENT PRIMARY KEY,
    academicYear VARCHAR(50),
    slipreferenceNo VARCHAR(50),
    date DATE,
    department VARCHAR(100),
    hod VARCHAR(100),
    headOfAccount VARCHAR(100),
    totalAmount DECIMAL(10,2),
    referenceNo VARCHAR(50),
    allotmentdate DATE,
    expenditure DECIMAL(10,2),
    amountClaimed DECIMAL(10,2),
    balance DECIMAL(10,2),
    remarks TEXT,
    paymentDetails TEXT,
    invoiceNo VARCHAR(50),
    total DECIMAL(10,2),
    fileNo VARCHAR(50),
    invoiceNo2 VARCHAR(50),
    invoiceDate DATE,
    tinNo VARCHAR(50),
    areaCode VARCHAR(50),
    gstn VARCHAR(50),
    productDescriptions TEXT,
    quantities TEXT,
    unitRates TEXT,
    amounts TEXT,
    CGSTs TEXT,
    SGSTs TEXT,
    grossamt DECIMAL(10,2),
    grandTotal DECIMAL(10,2),
    bankDetails VARCHAR(100),
    detailsEnteredIn VARCHAR(100),
    stockRegisterPageNo VARCHAR(50)
);
